#!/bin/bash
TYPE=$1
NAME=$2
i=0;
arr_counter=0;
METHODS=[]
for m in $*; do
	if [ "$i" -gt 1 ]; then
		METHODS[$arr_counter]=$m
		arr_counter=`expr $arr_counter + 1`
	fi
	i=`expr $i + 1`
done;


function create_model()
{
	echo "create app/models/$1.php"
	cat > "app/models/$1.php" <<content_wraper
<?php
class $1 extends tinly_model {
	public \$tbl = '$1';
	public static \$instance;
	public \$fields = array(
		'id' => array(
			'type' => 'int',
			'null' => false,
			'extra' => 'auto_increment',
			'primary_key' => 'true'
		),
	);
   // i() make model accessible, usage ex: $i::i()->fetchAll() {{{
   public static function i() { if (!isset(self::\$instance)) { \$c = __CLASS__; self::\$instance = new \$c(); } return self::\$instance; } 
	// }}}
}
?>
content_wraper

}


function create_controller()
{


	mkdir "app/views/$1"
	touch "app/views/$1/index.tpl.php"
	echo "creating views/$1"


	echo "creating app/controllers/$1_controller.php"
	cat > "app/controllers/$1_controller.php"<<content_wraper
<?php
class $1_controller extends tinly_controller
{
	// index() {{{
	public function index_()
	{
		\$this->tpl->assign(array(
			'page_title' => 'the index page',
			'_action' => 'index',
		));
	}// }}}
content_wraper

	echo "createing app/views/$1/index.tpl.php"
	cat > "app/views/$1/index.tpl.php"<<content_wraper
	<h1><?= \$page_title?></h1>
content_wraper

		for m in ${METHODS[*]}; do
			action="$m"_
			echo "createing app/views/$1/$m.tpl.php"
			touch "app/views/$1/$m.tpl.php"
			cat >> "app/controllers/$1_controller.php"<<content_wraper
	// $m() {{{
	public function $action()
	{
		\$this->tpl->assign(array(
			'page_title' => 'the $m page',
			'_action' => '$m',
		));

	} // }}}
content_wraper
		done;

		cat >> "app/controllers/$1_controller.php"<<content_wraper
}
?>
content_wraper
}


case $TYPE in
	"model")
	create_model "$NAME"
	;;
	"controller")
	create_controller "$NAME" $METHODS
	;;
	*)
	echo "usage: generate (model|controller) name_of"
	;;
esac
