#!/bin/bash
TYPE=$1
NAME=$2
i=0;
arr_counter=0;
METHODS=[]
for m in $*; do
	if [ "$i" -gt 0 ]; then
		METHODS[$arr_counter]=$m
		arr_counter=`expr $arr_counter + 1`
	fi
	i=`expr $i + 1`
done;


function create_model()
{
	echo "create models/$1.php"
	cat >> "app/models/$1.php" <<content_wraper
<?php
class $1 extends Base_Model {
	public \$tbl = '$1';
	public \$fields = array(
		'id' => array(
			'type' => 'int',
			'null' => false,
			'extra' => 'auto_increment',
			'primary_key' => 'true'
		),
	);
}
?>
content_wraper

}


function create_controller()
{


	mkdir "app/views/$1"
	touch "app/views/$1/index.tpl.php"
	echo "creating views/$1"
	echo "createing app/views/$1/index.tpl.php"
	cat > "app/views/$1/index.tpl.php"<<content_wraper
	<h1><?= \$page_title?></h1>
content_wraper


	echo "creating app/controllers/$1.php"
	cat > "app/controllers/$1_controller.php"<<content_wraper
<?php
class $1_Controller extends Base_Controller
{
	public function _index()
	{
		\$this->tpl->assign(array(
			'page_title' => 'the index page',
			'_action' => 'index',
		));
	}
content_wraper


		for m in ${METHODS[*]}; do
			touch "app/views/$1/$m.tpl.php"
			cat >> "app/controllers/$1_controller.php"<<content_wraper
	public function _$m()
	{
		\$this->tpl->assign(array(
			'page_title' => 'the $m page',
			'_action' => '$m',
		));

	}
content_wraper
		done;

		cat >> "app/controllers/$1_controller.php"<<content_wraper
}
?>
content_wraper
}


case $TYPE in
	"model")
	create_model "$NAME"
	;;
	"controller")
	create_controller "$NAME" $METHODS
	;;
	*)
	echo "usage: generate (model|controller) name_of"
	;;
esac
